// import { Poster, NavigationBar, FeatureCard, CardItem } from '../components/usu';
// import router from '@ohos.router'; // 导入路由模块
//
// @Component
// export struct HomeView {
//   // 控制首页导航项背景色
//   @State homeNavBgColor: string = '#ffffffff';
//
//   build() {
//     Column() {
//       // 可滚动内容区域
//       Scroll() {
//         Column() {
//           // 顶部“Hi~”文字
//           Text('Hi~')
//             .fontSize(32)
//             .width(320)
//             .margin({ top: 10, bottom: 5 });
//
//           // 书本图片组件
//           Poster()
//             .width(343)
//             .height(192)
//             .margin({ bottom: 10 });
//         }
//
//       }
//       .width('100%')
//       .height('100%')
//       //.alignItems(HorizontalAlign.Center)
//       .backgroundColor('#f4fafa')
//       .backgroundImagePosition(Alignment.Center)
//       .backgroundImageSize(ImageSize.Cover);
//     }
//   }
// }
